### ISSUE TITLE
Itens vanish after a player open the chest

### ISSUE THREAD

**Issue by MackleyMag** [christopherwalkerml/DeepStoragePlus#2]
There is an error that I don't know how to explain. I'm playing with some friends, and when a specific friend opens the chest the HD vanish and the chest gets reset. 
      If there is a hopper after the chest, (sometimes) the HD is saved, if not, god bye to all the items. All my others friends opens the chest and nothing like that happens. Just with this specific player. He can see the chest, the items inside, but when he closes the chest, it crashes, loose the items and the HD storage and he looses the access to the chest, if its locked.
    I think is because the player has en "_" after his nick.(MarcosVini_) I think it probably be it. No error is showed in console. I'm using version 1.6.15

**Comment by MackleyMag** [comment]
![image](https://user-images.githubusercontent.com/11464046/85489253-1d5c2c80-b5a6-11ea-90ed-978e1d25b289.png)
This is how the chest connected with the hopper to the deep storage chest looks like after my friend opens

**Comment by christopherwalkerml** [comment]
> There is an error that I don't know how to explain. I'm playing with some friends, and when a specific friend opens the chest the HD vanish and the chest gets reset.
> If there is a hopper after the chest, (sometimes) the HD is saved, if not, god bye to all the items. All my others friends opens the chest and nothing like that happens. Just with this specific player. He can see the chest, the items inside, but when he closes the chest, it crashes, loose the items and the HD storage and he looses the access to the chest, if its locked.
> I think is because the player has en "_" after his nick.(MarcosVini_) I think it probably be it. No error is showed in console. I'm using version 1.6.15

Are you able to test this on a fresh server? Perhaps there are plugin conflicts?
And can you give me steps to reproduce it?
What version of minecraft are you running?

**Comment by MackleyMag** [comment]
The steps is:
1- put the key on the chest that I want to use
2- put the Hd in the right place
3- set the permission to the friends to open the chest or open for all
4- let him go open. 

That’s all.

I’m gonna test in a fresh server by night today, but I was wondering if was plugin incompatibility. I’ll send a list of the plugins I use in my server.


ItemBox, LuckPerms, WorldEdit, EggCatcher, ColoredSigns, AngelChest, FastCraft, DragonEggDrop, EXPBank-6.0.0, DeepStoragePlus, ShulkerPacks, PlugMan, AutoCraftChest, ChestSort, Multiverse-Core, ProtocolLib, WorldGuard, MineTinker, SkinsRestorer, VoidGenerator, EditableSign, mcMMO, Vault, ID-Library, BloodInMinecraft, PluginHiderPlus, CustomRecipeAPI, InfernalMobs, Essentials, GChestShop, Herochat, AuthMe, BountyHunters, SilkSpawners, BetterSleeping3, frConomy, LockettePro, Lottery, MyPet, Jobs, RedProtect, TreeAssist, BuyRegion

**Comment by christopherwalkerml** [comment]
Please let me know if the problem persists even on a fresh server. If it does, you will have to check each one of your plugins and let me know which one is causing it so that I can look into fixing the incompatibility.

Scanning the names of the plugins, here are the ones I'd suggest testing first:

**ChestSort** for sure try this one first, Ive seen issues with this in the past. There's nothing I can do about it. It's on their end.

others to check:
ItemBox, EggCatcher, AngelChest, AutoCraftChest, GChestShop, LockettePro

**Comment by MackleyMag** [comment]
I tried all the solutions just tu check. Chestsort is the problem. I’ve just removed it from my server. Add this to the incompatibility list plugins in spigot just to anyone bother anymore. Thanks for the help

**Comment by Fundryi** [comment]
You can still use Chestort with Deep Storage, you just need to change the config a bit.

```
# when set to false, no player is allowed to enable automatic inventory sorting
# hotkeys will still work if enabled
allow-automatic-inventory-sorting: false

# Instead of automatic sorting, you can also use hotkeys (see below)
# when using an inventory to have it sorted immediately.
# You can disable this by setting this to false.
allow-sorting-hotkeys: true

# You can define which sorting hotkeys are enabled by default.
# Players can also enable/disable these shortcuts individually via /chestsort hotkeys
# Hotkeys that could interfere with Minecraft's normal behaviour (e.g.
# shift+left-click) only work on empty slots, so don't worry about them.
sorting-hotkeys:
  # Use middle click (mousewheel) on ANY inventory slot as hotkey
  middle-click: true
  # Use shift + left-click on any EMPTY inventory slot as hotkey
  shift-click: false
  # Use double left-click on any EMPTY inventory slot as hotkey
  double-click: false
  # Use shift + right-click on any EMPTY inventory slot as hotkey
  shift-right-click: false

# Additionally to sorting hotkeys, you can quickly unload your inventory into a chest and vice versa
# using left-click or right-click outside of a chest's inventory.
# A single click will only affect matching items (items that are already present in the other inventory)
# and a double click will try to store/take all items.
allow-additional-hotkeys: true

# You can define which additional hotkeys are enabled by default.
# Players can also enable/disable these shortcuts individually via /chestsort hotkeys
additional-hotkeys:
  # Use left-click outside inventory to quickly put matching items from your inventory (except hotbar)
  # into the chest. Use left-double-click to put everything except your hotbar into the chest.
  left-click: false
  # Use right-click outside inventory to quickly take all matching items from the chest into your
  # inventory. Use right-double-click to take all items out of the chest.
  right-click: false
```
